name: Flutter Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Create project
        run: | 
              flutter pub get
              flutter build web --release
              git config --global user.email luannery@live.com
              git config --global user.name Yren 
              cd build/web
              git config --global init.defaultBranch gh-pages
              git init
              git remote add origin https://${{secrets.PRIORIZZA}}@github.com/imperiousnery/priorizza.git
              git checkout -b gh-pages
              git add --all
              git commit -m "update"
              git push origin gh-pages -f
